---
title: "个人简介"
author: "Xingjie Shi"
date: 2015-07-23T21:13:14-05:00
categories: ["R"]
#tags: ["R Markdown", "plot", "regression"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```


***

<div class = "row">
  
<div class = "col-md-6">
```{r, echo=FALSE}
library(png)
library(grid)
img <- readPNG("/Users/xingjieshi/Cloud/PersonFiles/homepage/static/WechatIMG349.png")
grid.raster(img)
```
</div>

<div class = "col-md-6">
<br><br>

- __史兴杰__
- 南京财经大学，统计系副教授(校聘教授)
- 国际统计学会推选会士（ISI Elected member）
- 现场统计研究会环境与资源统计学会理事
- 研究方向：组学遗传学统计建模、高维大数据统计计算、生存分析
- 通讯地址：江苏省南京财经大学德经楼219
- 邮箱: shixingjie0615@gmail.com

</div>

</div>




***
 


<style>
div.blue { background-color:#E3AF63; border-radius: 5px; padding: 20px;}
</style>
<div class = "blue">
  |         |   |         |                  |            |              |
  |:-------:|:-:|:-------:|:----------------:|:----------:|:------------:|
  | 2009.09 |---| 2014.06$~~~~$ | 上海财经大学$~~~~~$ |   统计学   |博士(硕博连读)|
  | 2012.09  |---| 2014.04$~~~~$ |耶鲁大学$~~~~~$|生物统计学|联合培养|
  | 2005.09  |---| 2009.06$~~~~$ |南京审计学院$~~~~~$|数学与应用数学|本科|

</div>
 