---
title: "Publication"
author: "Frida Gomam"
date: '2015-07-23T21:13:14-05:00'
categories: R
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

***

#. 
Q. Cheng, T. Qiu, X. Chai, B. Sun, Y. Xia, __X. Shi$^\ast$__, J. Liu$^\ast$ (2021) MR-Corr$^2$: a two-sample Mendelian randomization method that accounts for correlated horizontal pleiotropy using correlated instrumental variants. [R Package](https://github.com/QingCheng0218/MR.Corr2)
 
#. 
X. Zhang, X. Liu, __X. Shi$^\ast$__ (2021) Model Selection for Varying Coefficient Nonparametric Transformation Model. [R package](https://github.com/XiaoZhangryy/GFabs)

#.
__X. Shi__, X. Chai, Y. Yang, Q. Cheng, Y. Jiao, H Chen, J. Huang, C. Yang, J. Liu J (2020) [A tissue-specific collaborative mixed model for jointly analyzing multiple tissues in transcriptome-wide association studies](https://academic.oup.com/nar/article/48/19/e109/5911964). $\underline{Nucleic \space Acids \space Research}$. 48(19): e109. [R Package](https://github.com/XingjieShi/TisCoMM).

#.
__史兴杰__, 王赛旎 \& 李扬 (2020) [高维数据的稳健二分类方法](https://tjyj.stats.gov.cn/CN/10.19343/j.cnki.11-1302/c.2020.09.009), $\underline{统计研究}$, 37(9): 95-105


#. 
__X. Shi__, S. Ma, Y. Huang (2020) [Promoting sign consistency in the cure model estimation and selection](https://journals.sagepub.com/doi/abs/10.1177/0962280218820356?rfr_dat=cr_pub%3Dpubmed&url_ver=Z39.88-2003&rfr_id=ori%3Arid%3Acrossref.org&journalCode=smma). $\underline{Statistical \space Methods \space in \space Medical \space Research}$. 29(1):15-28. [Software](https://github.com/shuanggema/SCinCRM).

#. 
__X. Shi__, Y. Jiao, Y. Yang, Q. Cheng, C. Yang, X. Lin, J. Liu (2019) [VIMCO: variational inference for multiple
correlated outcomes in genome-wide association studies](https://academic.oup.com/bioinformatics/article-abstract/35/19/3693/5372680?redirectedFrom=fulltext). $\underline{Bioinformatics}$, 35(19): 3693-3700. [R Package](https://github.com/XingjieShi/VIMCO).
 
#.
孙怡凡, 吴梦云 \& __史兴杰__ (2019) [高维大数据基因网络中的社区发现--以NC方法为例](http://tjyj.stats.gov.cn/CN/Y2019/V36/I3/124), $\underline{统计研究}$. 36(3), 124-128.

#.
S. Wang, __X. Shi__, M. & S. Ma (2019) [Horizontal and vertical integrative analysis methods for mental disorders omics data](https://www.nature.com/articles/s41598-019-49718-5). $\underline{Scientific \space Reports}$, 9: 13430.
 
#. 
Y. Yang, __X. Shi__, Y. Jiao, J. Huang, M. Chen, X. Zhou, L. Sun, X. Lin, C. Yang, J. Liu (2019) [CoMM-S$^2$: a collaborative mixed model using summary statistics in transcriptome-wide association studies](https://academic.oup.com/bioinformatics/advance-article-abstract/doi/10.1093/bioinformatics/btz880/5637753?redirectedFrom=fulltext). $\underline{Bioinformatics}$, preprint.  [R Package](https://github.com/gordonliu810822/CoMM). 41(8): 779-789.
 

#.
__X. Shi__, Y. Huang, J. Huang \& S. Ma (2018). [A Forward and Backward Stagewise Algorithm for Nonconvex Loss Functions with Adaptive Lasso](https://www.sciencedirect.com/science/article/pii/S0167947318300549). $\underline{Computational \space Statistics \space and \space Data \space Analysis}$, 124: 235-251. [R Package](https://github.com/Tesla-Xiao/GFabs).

#.
H. Chai$^\#$, __X. Shi__$^\#$, Q. Zhang, Q. Zhao, Y. Huang \& S. Ma (2017) [Analysis of cancer gene expression data with an assisted robust marker identification approach](https://onlinelibrary.wiley.com/doi/abs/10.1002/gepi.22066).  $\underline{Genetic \space Epidemiology}$, 41(8): 779-789.

#.
Y. Jiang$^\#$, __X. Shi__$^\#$, Q. Zhao, M. Krauthammer, BE Rothberg, S. Ma (2016) [Integrated analysis of multidimensional omics data on cutaneous melanoma prognosis](https://www.sciencedirect.com/science/article/pii/S088875431630026X?via%3Dihub).  $\underline{Genomics}$, 107(6): 223-30.

#.
J. Liu, C. Yang, __X. Shi__, C. Li, J. Huang, H. Zhao \& S. Ma. (2016) [Analyzing Association Mapping in Pedigree-Based GWAS Using a Penalized Multitrait Mixed Model](https://onlinelibrary.wiley.com/doi/abs/10.1002/gepi.21975). $\underline{Genetic \space Epidemiology}$, 40(5): 382-393.

#.
__X. Shi__, Q. Zhao, J. Huang, Y. Xie \& S. Ma (2015) [Deciphering the association between gene expression and copy number alteration using a sparse double Laplacian shrinkage approach](https://academic.oup.com/bioinformatics/article/31/24/3977/198399). $\underline{Bioinformatics}$, 31(24): 3977-3983.

#.
Q. Zhao, __X. Shi__, J. Huang, J. Liu, Y. Li, S. (2015). [Integrative analysis of "-omics" data using penalty functions](https://onlinelibrary.wiley.com/doi/abs/10.1002/wics.1322). $\underline{WIREs \space Computational \space Statistics}$, 7(1): 99-108.

#.
__X. Shi__$^\#$, H. Yi$^\#$, \& S. Ma (2015) [Measures for the degree of overlap of gene signatures and applications to TCGA](https://academic.oup.com/bib/article/16/5/735/217366). $\underline{Briefings \space in \space Bioinformatics}$, 16(5): 735-744.

#.
C. Wu, __X. Shi__, Y. Cui, S. Ma (2015) [A penalized robust semiparametric approach for gene–environment interactions](https://onlinelibrary.wiley.com/doi/abs/10.1002/sim.6609). $\underline{Statistics \space in \space Medicine}$, 34 (30): 4016–4030.

#. 
Q. Zhao$^\#$, __X. Shi__$^\#$, Y. Xie, J. Huang, B. Shia \& S. Ma (2015) [Combining Multidimensional Genomic Measurements for Predicting Cancer Prognosis: Observations from TCGA](https://academic.oup.com/bib/article/16/2/291/246070). $\underline{Briefings \space in \space Bioinformatics}$, 16(2): 291-303.

#. 
__X. Shi__, J. Liu, J. Huang, Y. Zhou, B. Shia \& S. Ma (2014) [Integrative Analysis of Cancer Prognosis Data with Contrasted Group Bridge Penalization](https://onlinelibrary.wiley.com/doi/abs/10.1002/gepi.21781). $\underline{Genetic \space Epidemiology}$, 38(2): 141-151.

#.
__X. Shi__, J. Liu, J. Huang, Y. Zhou, Y. Xie \& S. Ma (2014) [A Penalized Robust Method for identifying Gene-Environment Interactions](https://onlinelibrary.wiley.com/doi/abs/10.1002/gepi.21795). $\underline{Genetic \space Epidemiology}$. 38(3): 220-230.

#. 
__史兴杰__ \& 周勇 (2014) [房地产泡沫检验的Switching AR模型](http://www.sysengi.com/CN/abstract/abstract110439.shtml). $\underline{系统工程理论与实践}$, 34(3): 676-682.


#.
__X. Shi__, S. Shen, J. Liu, J. Huang, Y. Zhou \& S. Ma (2013) [Similarity of Markers Identified from Cancer Gene Expression Studies: Observations from GEO](https://academic.oup.com/bib/article/15/5/671/2422299). $\underline{Briefings \space in \space Bioinformatics}$. 15(5): 671-684.

#. 
刘玉涛, __史兴杰__ \& 周勇 (2013)  [左截断右删失数据下光滑分布函数估计效率](http://www.actamath.com/CN/abstract/abstract22072.shtml). $\underline{数学学报}$, 56(5): 625-636.


 
